window.SICO_COLORS = [
  { code: "10", name: "Фіолетовий" },
  { code: "20", name: "Синій" },
  { code: "20/B", name: "Синій Flex" },
  { code: "P20/5", name: "Pantone Blue" },
  { code: "22", name: "Ультрамарин" },
  { code: "24", name: "Блакитний" },
  { code: "26", name: "Світло-блакитний" },
  { code: "P26/2", name: "Pantone Blue 2" },
  { code: "27", name: "Бірюзовий" },
  { code: "30", name: "Темно-зелений" },
  { code: "31", name: "Зелений" },
  { code: "32", name: "Яскраво-зелений" },
  { code: "33", name: "Зелений трава" },
  { code: "40", name: "Жовтий" },
  { code: "41", name: "Цитриновий" },
  { code: "42", name: "Медовий" },
  { code: "50", name: "Помаранчевий" },
  { code: "51", name: "Світло-помаранчевий" },
  { code: "56", name: "Червоний" },
  { code: "60", name: "Темно-червоний" },
  { code: "P60/38", name: "Pantone Red" },
  { code: "61", name: "Малиновий" },
  { code: "P61/15", name: "Pantone Magenta" },
  { code: "70", name: "Магента" },
  { code: "80", name: "Коричневий" },
  { code: "81", name: "Темно-коричневий" },
  { code: "82", name: "Бежевий" },
  { code: "90", name: "Білий" },
  { code: "91", name: "Криючий білий" },
  { code: "100", name: "Чорний" },
  { code: "110", name: "Срібло" },
  { code: "120", name: "Золото" },
  { code: "130", name: "Флуо жовтий" },
  { code: "131", name: "Флуо оранж" },
  { code: "132", name: "Флуо червоний" },
  { code: "133", name: "Флуо рожевий" },
  { code: "134", name: "Флуо зелений" },
  { code: "135", name: "Флуо синій" },
  { code: "136", name: "Флуо блакитний" },
  { code: "140", name: "CMYK Yellow" },
  { code: "141", name: "CMYK Cyan" },
  { code: "142", name: "CMYK Magenta" },
  { code: "143", name: "CMYK Black" }
];
